const participants = {
  "ceiling": {
    "a": "10",
    "b": "10",
    "c": "20",
    "d": "20",
    "e": "30",
    "f": "30"
  },
  "participants": [
    {
      "name": "Ivan Novikov",
      "title": "Cloud Platform Architect",
      "country": "Russia",
      "a": "8",
      "b": "1",
      "c": "20",
      "d": "16",
      "e": "23",
      "f": "19.005",
    },
    {
      "name": "Michael Araya",
      "title": "Software Architect",
      "country": "United States",
      "a": "9",
      "b": "3",
      "c": "11",
      "d": "10",
      "e": "25",
      "f": "24.131",
      "undefined": "82"
    },
    {
      "name": "Alexandr Popov",
      "title": "Senior Frontend Engineer",
      "country": "Ukraine",
      "a": "8",
      "b": "0",
      "c": "19",
      "d": "19",
      "e": "29",
      "f": "6.237",
      "undefined": "81"
    },
    {
      "name": "Anton Sergeev",
      "title": "OpenStack Operations Engineer",
      "country": "Russia",
      "a": "0",
      "b": "9",
      "c": "10",
      "d": "8",
      "e": "24",
      "f": "28.795",
      "undefined": "79"
    },
    {
      "name": "Pavel Orlov",
      "title": "Java Chief Architect",
      "country": "Russia",
      "a": "10",
      "b": "0",
      "c": "9",
      "d": "6",
      "e": "27",
      "f": "26.987",
      "undefined": "78"
    },
    {
      "name": "Andrii Voloshyn",
      "title": "IT Architect",
      "country": "Ukraine",
      "a": "4",
      "b": "9",
      "c": "13",
      "d": "20",
      "e": "5",
      "f": "27.765",
      "undefined": "78"
    },
    {
      "name": "Andrey Chernyshov",
      "title": "Systems Architect",
      "country": "Russia",
      "a": "4",
      "b": "2",
      "c": "17",
      "d": "8",
      "e": "24",
      "f": "23.711",
      "undefined": "78"
    },
    {
      "name": "Pavel Yukhnevich",
      "title": "OpenStack Operations Engineer",
      "country": "Belarus",
      "a": "4",
      "b": "0",
      "c": "6",
      "d": "17",
      "e": "30",
      "f": "21.321",
      "undefined": "78"
    },
    {
      "name": "Bao Liu",
      "title": "Lead Developer",
      "country": "China",
      "a": "10",
      "b": "6",
      "c": "15",
      "d": "16",
      "e": "4",
      "f": "27.225",
      "undefined": "78"
    },
    {
      "name": "John Gee",
      "title": "Cloud Solutions Architect",
      "country": "United States",
      "a": "2",
      "b": "6",
      "c": "18",
      "d": "14",
      "e": "24",
      "f": "13.559",
      "undefined": "77"
    },
    {
      "name": "Oleksii Kovalchuk",
      "title": "OpenStack Operations Engineer",
      "country": "Ukraine",
      "a": "3",
      "b": "10",
      "c": "19",
      "d": "18",
      "e": "7",
      "f": "20.256",
      "undefined": "77"
    },
    {
      "name": "Yuki Saito",
      "title": "Senior Architect",
      "country": "Japan",
      "a": "6",
      "b": "8",
      "c": "4",
      "d": "19",
      "e": "21",
      "f": "18.388",
      "undefined": "76"
    },
    {
      "name": "Song Shi",
      "title": "Senior Software Engineer",
      "country": "China",
      "a": "3",
      "b": "7",
      "c": "16",
      "d": "16",
      "e": "9",
      "f": "25.382",
      "undefined": "76"
    },
    {
      "name": "Kohei Yamada",
      "title": "Architect",
      "country": "Japan",
      "a": "5",
      "b": "8",
      "c": "16",
      "d": "13",
      "e": "9",
      "f": "25.112",
      "undefined": "76"
    },
    {
      "name": "Jin Li",
      "title": "Cloud Platform Architect",
      "country": "China",
      "a": "10",
      "b": "1",
      "c": "6",
      "d": "18",
      "e": "28",
      "f": "11.383",
      "undefined": "74"
    },
    {
      "name": "Bo Fu",
      "title": "Cloud Solutions Architect",
      "country": "China",
      "a": "9",
      "b": "4",
      "c": "15",
      "d": "7",
      "e": "8",
      "f": "29.512",
      "undefined": "72"
    },
    {
      "name": "Alexander Shevchuk",
      "title": "Lead Frontend Developer",
      "country": "Ukraine",
      "a": "5",
      "b": "0",
      "c": "8",
      "d": "12",
      "e": "23",
      "f": "22.991",
      "undefined": "70"
    },
    {
      "name": "Saras Gupta",
      "title": "OpenStack Operations Engineer",
      "country": "India",
      "a": "9",
      "b": "7",
      "c": "17",
      "d": "18",
      "e": "3",
      "f": "15.481",
      "undefined": "69"
    },
    {
      "name": "Sergey Fomin",
      "title": "Systems Architect",
      "country": "Russia",
      "a": "5",
      "b": "4",
      "c": "6",
      "d": "13",
      "e": "19",
      "f": "21.117",
      "undefined": "68"
    },
    {
      "name": "Pete Warden",
      "title": "Java Chief Architect",
      "country": "United States",
      "a": "8",
      "b": "7",
      "c": "2",
      "d": "16",
      "e": "4",
      "f": "30.009",
      "undefined": "67"
    },
    {
      "name": "Stephen Grider",
      "title": "Java Chief Architect",
      "country": "United States",
      "a": "5",
      "b": "10",
      "c": "13",
      "d": "1",
      "e": "10",
      "f": "26.161",
      "undefined": "65"
    },
    {
      "name": "Piyush Agarwal",
      "title": "Software Architect",
      "country": "India",
      "a": "0",
      "b": "8",
      "c": "13",
      "d": "14",
      "e": "5",
      "f": "25.007",
      "undefined": "65"
    },
    {
      "name": "Yan Wang",
      "title": "IT Architect",
      "country": "Japan",
      "a": "8",
      "b": "9",
      "c": "13",
      "d": "0",
      "e": "17",
      "f": "18.001",
      "undefined": "65"
    },
    {
      "name": "Dmitry Kozlov",
      "title": "Senior Systems Engineer",
      "country": "Belarus",
      "a": "7",
      "b": "8",
      "c": "7",
      "d": "2",
      "e": "12",
      "f": "28.821",
      "undefined": "64"
    },
    {
      "name": "Dmitry Ivanov",
      "title": "Software Architect",
      "country": "Belarus",
      "a": "3",
      "b": "10",
      "c": "0",
      "d": "19",
      "e": "20",
      "f": "12.639",
      "undefined": "64"
    },
    {
      "name": "Yan Cheng",
      "title": "Senior Systems Engineer",
      "country": "China",
      "a": "4",
      "b": "7",
      "c": "12",
      "d": "6",
      "e": "30",
      "f": "5.281",
      "undefined": "64"
    },
    {
      "name": "Nikita Popov",
      "title": "Senior Systems Engineer",
      "country": "Russia",
      "a": "8",
      "b": "9",
      "c": "14",
      "d": "1",
      "e": "2",
      "f": "29.107",
      "undefined": "63"
    },
    {
      "name": "Sergey Larin",
      "title": "Software Architect",
      "country": "Russia",
      "a": "0",
      "b": "3",
      "c": "10",
      "d": "10",
      "e": "26",
      "f": "13.213",
      "undefined": "62"
    },
    {
      "name": "Naman Jain",
      "title": "Senior Software Engineer",
      "country": "India",
      "a": "9",
      "b": "9",
      "c": "10",
      "d": "5",
      "e": "14",
      "f": "14.005",
      "undefined": "61"
    },
    {
      "name": "Joey Woodson",
      "title": "Senior Architect",
      "country": "United States",
      "a": "9",
      "b": "1",
      "c": "1",
      "d": "2",
      "e": "22",
      "f": "24.722",
      "undefined": "59"
    },
    {
      "name": "Nick Leisure",
      "title": "DevOps Architect",
      "country": "United States",
      "a": "2",
      "b": "4",
      "c": "19",
      "d": "4",
      "e": "7",
      "f": "23.307",
      "undefined": "59"
    },
    {
      "name": "Alexander Sidorov",
      "title": "Software Architect",
      "country": "Belarus",
      "a": "0",
      "b": "10",
      "c": "10",
      "d": "6",
      "e": "4",
      "f": "28.955",
      "undefined": "58"
    },
    {
      "name": "Abdur Rahman",
      "title": "Senior Architect",
      "country": "India",
      "a": "7",
      "b": "0",
      "c": "1",
      "d": "9",
      "e": "29",
      "f": "12.704",
      "undefined": "58"
    },
    {
      "name": "Dmitry Nikolaev",
      "title": "Lead Developer",
      "country": "Belarus",
      "a": "4",
      "b": "0",
      "c": "9",
      "d": "13",
      "e": "16",
      "f": "16.661",
      "undefined": "58"
    },
    {
      "name": "Alexey Kryukov",
      "title": "Senior Architect",
      "country": "Russia",
      "a": "6",
      "b": "7",
      "c": "16",
      "d": "11",
      "e": "6",
      "f": "11.329",
      "undefined": "57"
    },
    {
      "name": "Vladimir Pavlov",
      "title": "Java Chief Architect",
      "country": "Russia",
      "a": "8",
      "b": "0",
      "c": "7",
      "d": "0",
      "e": "16",
      "f": "24.598",
      "undefined": "55"
    },
    {
      "name": "Aman Mittal",
      "title": "Architect",
      "country": "India",
      "a": "0",
      "b": "6",
      "c": "16",
      "d": "0",
      "e": "3",
      "f": "30.321",
      "undefined": "55"
    },
    {
      "name": "Maxim Zhukov",
      "title": "Lead Developer",
      "country": "Belarus",
      "a": "9",
      "b": "1",
      "c": "20",
      "d": "11",
      "e": "1",
      "f": "12.557",
      "undefined": "54"
    },
    {
      "name": "Hanh Nguyen",
      "title": "Cloud Platform Architect",
      "country": "Japan",
      "a": "4",
      "b": "7",
      "c": "15",
      "d": "5",
      "e": "18",
      "f": "4.811",
      "undefined": "53"
    },
    {
      "name": "Harsh Bajaj",
      "title": "Senior Engineer",
      "country": "India",
      "a": "8",
      "b": "10",
      "c": "7",
      "d": "20",
      "e": "3",
      "f": "3.719",
      "undefined": "51"
    },
    {
      "name": "Edwin Chen",
      "title": "Senior Software Engineer",
      "country": "United States",
      "a": "7",
      "b": "5",
      "c": "1",
      "d": "4",
      "e": "5",
      "f": "26.512",
      "undefined": "48"
    },
    {
      "name": "Dmitry Erokhin",
      "title": "Senior Frontend Engineer",
      "country": "Russia",
      "a": "6",
      "b": "6",
      "c": "7",
      "d": "13",
      "e": "4",
      "f": "9.979",
      "undefined": "45"
    },
    {
      "name": "Prakhar Agrawal",
      "title": "OpenStack Operations Engineer",
      "country": "India",
      "a": "6",
      "b": "9",
      "c": "3",
      "d": "10",
      "e": "8",
      "f": "7.756",
      "undefined": "43"
    },
    {
      "name": "Adarsh Shah",
      "title": "IT Architect",
      "country": "India",
      "a": "10",
      "b": "6",
      "c": "7",
      "d": "0",
      "e": "1",
      "f": "18.551",
      "undefined": "42"
    },
    {
      "name": "Dmytro Morozov",
      "title": "Software Architect",
      "country": "Ukraine",
      "a": "10",
      "b": "0",
      "c": "3",
      "d": "4",
      "e": "4",
      "f": "17.684",
      "undefined": "38"
    },
    {
      "name": "Andrey Solovyev",
      "title": "DevOps Architect",
      "country": "Russia",
      "a": "4",
      "b": "4",
      "c": "12",
      "d": "5",
      "e": "9",
      "f": "4.119",
      "undefined": "38"
    },
    {
      "name": "Alexander Molchanov",
      "title": "Java Chief Architect",
      "country": "Russia",
      "a": "7",
      "b": "8",
      "c": "2",
      "d": "0",
      "e": "3",
      "f": "17.012",
      "undefined": "37"
    },
    {
      "name": "Ivan Voronov",
      "title": "Lead Developer",
      "country": "Ukraine",
      "a": "0",
      "b": "9",
      "c": "3",
      "d": "2",
      "e": "15",
      "f": "3.488",
      "undefined": "32"
    },
    {
      "name": "Sergey Krasnov",
      "title": "Lead Frontend Developer",
      "country": "Russia",
      "a": "6",
      "b": "0",
      "c": "0",
      "d": "5",
      "e": "14",
      "f": "7.301",
      "undefined": "32"
    },
    {
      "name": "Alexander Alekseev",
      "title": "DevOps Architect",
      "country": "Russia",
      "a": "8",
      "b": "0",
      "c": "15",
      "d": "0",
      "e": "0",
      "f": "0.733",
      "undefined": "23"
    },
    {
      "name": "Sumit Bansal",
      "title": "Software Architect",
      "country": "India",
      "a": "5",
      "b": "2",
      "c": "0",
      "d": "14",
      "e": "0",
      "f": "0.012",
      "undefined": "21"
    },
    {
      "name": "Xin Wang",
      "title": "Java Chief Architect",
      "country": "China",
      "a": "3",
      "b": "3",
      "c": "14",
      "d": "0",
      "e": "0",
      "f": "0.511",
      "undefined": "20"
    },
    {
      "name": "Yue Hu",
      "title": "Software Architect",
      "country": "United States",
      "a": "7",
      "b": "2",
      "c": "11",
      "d": "0",
      "e": "0",
      "f": "0.256",
      "undefined": "20"
    },
    {
      "name": "Sweta Rai",
      "title": "DevOps Architect",
      "country": "India",
      "a": "2",
      "b": "5",
      "c": "0",
      "d": "12",
      "e": "0",
      "f": "0.882",
      "undefined": "19"
    },
    {
      "name": "Shuai Yuan",
      "title": "Lead Developer",
      "country": "United States",
      "a": "1",
      "b": "9",
      "c": "7",
      "d": "0",
      "e": "0",
      "f": "0.418",
      "undefined": "17"
    },
    {
      "name": "Sheng Gao",
      "title": "Software Architect",
      "country": "China",
      "a": "3",
      "b": "8",
      "c": "5",
      "d": "0",
      "e": "0",
      "f": "0.015",
      "undefined": "16"
    },
    {
      "name": "Aditya Aggarwal",
      "title": "Software Architect",
      "country": "India",
      "a": "8",
      "b": "2",
      "c": "3",
      "d": "0",
      "e": "0",
      "f": "0.205",
      "undefined": "13"
    },
    {
      "name": "Li Tan",
      "title": "Java Chief Architect",
      "country": "China",
      "a": "9",
      "b": "2",
      "c": "2",
      "d": "0",
      "e": "0",
      "f": "0.201",
      "undefined": "13"
    },
    {
      "name": "Deepak Giri",
      "title": "Architect",
      "country": "India",
      "a": "3",
      "b": "1",
      "c": "7",
      "d": "0",
      "e": "0",
      "f": "0.398",
      "undefined": "11"
    },
    {
      "name": "Fan Bai",
      "title": "DevOps Architect",
      "country": "China",
      "a": "2",
      "b": "2",
      "c": "5",
      "d": "0",
      "e": "0",
      "f": "0.081",
      "undefined": "9"
    }
  ]
};